### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by longlongago2** [longlongago2/arch-editor#4]
@longlongago2 will develop these functions

***

- [ ] support [styled-components](https://styled-components.com/): so we can change theme via props.

- [ ] support rich table: choose rows and columns, merge cell, cell support rich-text.

- [ ] support emoji.

- [ ] support audio/video.
- [ ] support blockquote.

- [ ] support code-block.

- [ ] support i18n config.
